Nebb.WebApi/Controllers/FlightInfoesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nebb.Data.Models;

namespace Nebb.WebApi.Controllers
{
    public class FlightInfoesController : Controller
    {
        private readonly NebbContext _context;

        public FlightInfoesController(NebbContext context)
        {
            _context = context;
        }

        // GET: FlightInfoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.FlightInfo.ToListAsync());
        }

        // GET: FlightInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightInfo = await _context.FlightInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flightInfo == null)
            {
                return NotFound();
            }

            return View(flightInfo);
        }

        // GET: FlightInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FlightInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Origin,Destination,Departure,ReturnDay")] FlightInfo flightInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flightInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flightInfo);
        }

        // GET: FlightInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightInfo = await _context.FlightInfo.FindAsync(id);
            if (flightInfo == null)
            {
                return NotFound();
            }
            return View(flightInfo);
        }

        // POST: FlightInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Origin,Destination,Departure,ReturnDay")] FlightInfo flightInfo)
        {
            if (id != flightInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flightInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightInfoExists(flightInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flightInfo);
        }

        // GET: FlightInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightInfo = await _context.FlightInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flightInfo == null)
            {
                return NotFound();
            }

            return View(flightInfo);
        }

        // POST: FlightInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flightInfo = await _context.FlightInfo.FindAsync(id);
            _context.FlightInfo.Remove(flightInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightInfoExists(int id)
        {
            return _context.FlightInfo.Any(e => e.Id == id);
        }
    }
}

Nebb.WebApi/Controllers/PassengerInfoesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nebb.Data.Models;

namespace Nebb.WebApi.Controllers
{
    public class PassengerInfoesController : Controller
    {
        private readonly NebbContext _context;

        public PassengerInfoesController(NebbContext context)
        {
            _context = context;
        }

        // GET: PassengerInfoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.PassengerInfo.ToListAsync());
        }

        // GET: PassengerInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengerInfo = await _context.PassengerInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (passengerInfo == null)
            {
                return NotFound();
            }

            return View(passengerInfo);
        }

        // GET: PassengerInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PassengerInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,DateOfBirth,Passport,LoyalMemberId,UseLoyalMember")] PassengerInfo passengerInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(passengerInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(passengerInfo);
        }

        // GET: PassengerInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengerInfo = await _context.PassengerInfo.FindAsync(id);
            if (passengerInfo == null)
            {
                return NotFound();
            }
            return View(passengerInfo);
        }

        // POST: PassengerInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,DateOfBirth,Passport,LoyalMemberId,UseLoyalMember")] PassengerInfo passengerInfo)
        {
            if (id != passengerInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(passengerInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PassengerInfoExists(passengerInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(passengerInfo);
        }

        // GET: PassengerInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengerInfo = await _context.PassengerInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (passengerInfo == null)
            {
                return NotFound();
            }

            return View(passengerInfo);
        }

        // POST: PassengerInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var passengerInfo = await _context.PassengerInfo.FindAsync(id);
            _context.PassengerInfo.Remove(passengerInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PassengerInfoExists(int id)
        {
            return _context.PassengerInfo.Any(e => e.Id == id);
        }
    }
}

Nebb.WebApi/Controllers/TicketsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nebb.Data.Models;

namespace Nebb.WebApi.Controllers
{
    public class TicketsController : Controller
    {
        private readonly NebbContext _context;

        public TicketsController(NebbContext context)
        {
            _context = context;
        }

      //  GET: Tickets
        public async Task<IActionResult> Index()
        {
            var nebbContext = _context.Ticket.Include(t => t.Flight).Include(t => t.Passenger);
            return View(await nebbContext.ToListAsync());
        }

       // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Flight)
                .Include(t => t.Passenger)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

       // GET: Tickets/Create
        public IActionResult Create()
        {
            ViewData["FlightId"] = new SelectList(_context.FlightInfo, "Id", "Destination");
            ViewData["PassengerId"] = new SelectList(_context.PassengerInfo, "Id", "FirstName");
            return View();
        }

        // POST: Tickets/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FreeCarry,CheckedIn,TrolleyBag,PassengerId,FlightId")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlightId"] = new SelectList(_context.FlightInfo, "Id", "Destination", ticket.FlightId);
            ViewData["PassengerId"] = new SelectList(_context.PassengerInfo, "Id", "FirstName", ticket.PassengerId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["FlightId"] = new SelectList(_context.FlightInfo, "Id", "Destination", ticket.FlightId);
            ViewData["PassengerId"] = new SelectList(_context.PassengerInfo, "Id", "FirstName", ticket.PassengerId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FreeCarry,CheckedIn,TrolleyBag,PassengerId,FlightId")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlightId"] = new SelectList(_context.FlightInfo, "Id", "Destination", ticket.FlightId);
            ViewData["PassengerId"] = new SelectList(_context.PassengerInfo, "Id", "FirstName", ticket.PassengerId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Flight)
                .Include(t => t.Passenger)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Ticket.FindAsync(id);
            _context.Ticket.Remove(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Ticket.Any(e => e.Id == id);
        }
    }
}

Nebb.WebApi/Views/Tickets/Create.cshtml
@model Nebb.Data.Models.Ticket

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create ticket</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="FreeCarry" />Free carry-on bag #</label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="CheckedIn" />Checked-in bag #</label>
            </div>
            <div class="form-group">
                <label asp-for="TrolleyBag" class="control-label">Trolley Bag#</label>
                <input asp-for="TrolleyBag" class="form-control" />
                <span asp-validation-for="TrolleyBag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassengerId" class="control-label">Choose your profile</label>
                <select asp-for="PassengerId" class ="form-control" asp-items="ViewBag.PassengerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FlightId" class="control-label">Choose your flight</label>
                <select asp-for="FlightId" class ="form-control" asp-items="ViewBag.FlightId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<div class="form-group">
    <input type="button" value="Reserver Flight" class="btn btn-primary" onclick="window.location='@Url.Action("Create", "FlightInfoes")'" />
    <input type="button" value="List of Flights" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "FlightInfoes")'" />
    <input type="button" value="Create Profile" class="btn btn-primary" onclick="window.location='@Url.Action("Create", "PassengerInfoes")'" />
    <input type="button" value="List of Profiles" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "PassengerInfoes")'" />
</div>

Nebb.WebApi/Views/Tickets/Delete.cshtml
@model Nebb.Data.Models.Ticket

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete Ticket</h1>

<h3>Are you sure you want to delete this ticket?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Free carry-on bag #</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FreeCarry)
        </dd>
        <dt class="col-sm-2">Checked-in bag #</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckedIn)
        </dd>
        <dt class="col-sm-2">Trolley Bag#</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrolleyBag)
        </dd>
        <dt class = "col-sm-2">Destination</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flight.Destination)
        </dd class>
        <dt class = "col-sm-2">Profile</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Passenger.FirstName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Nebb.WebApi/Views/Tickets/Details.cshtml
@model Nebb.Data.Models.Ticket

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details for ticket</h1>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Free carry-on bag #</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FreeCarry)
        </dd>
        <dt class="col-sm-2">Checked-in bag #</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckedIn)
        </dd>
        <dt class="col-sm-2">Trolley Bag#</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrolleyBag)
        </dd>
        <dt class = "col-sm-2">Destination</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flight.Destination)
        </dd>
        <dt class = "col-sm-2">Profile Name</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Passenger.FirstName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<div class="form-group">
    <input type="button" value="List of Passengers" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "PassengerInfoes")'" />
    <input type="button" value="List of Flights" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "FlightInfoes")'" />
</div>

Nebb.WebApi/Views/Tickets/Edit.cshtml
@model Nebb.Data.Models.Ticket

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit ticket</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="FreeCarry" />Free carry-on bag #</label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="CheckedIn" />Checked-in bag #</label>
            </div>
            <div class="form-group">
                <label asp-for="TrolleyBag" class="control-label">Trolley Bag#</label>
                <input asp-for="TrolleyBag" class="form-control" />
                <span asp-validation-for="TrolleyBag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassengerId" class="control-label">Choose your profile</label>
                <select asp-for="PassengerId" class="form-control" asp-items="ViewBag.PassengerId"></select>
                <span asp-validation-for="PassengerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightId" class="control-label">Choose destination</label>
                <select asp-for="FlightId" class="form-control" asp-items="ViewBag.FlightId"></select>
                <span asp-validation-for="FlightId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Nebb.WebApi/Views/Tickets/Index.cshtml
@model IEnumerable<Nebb.Data.Models.Ticket>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List of Tickets</h1>

<p>
    <a asp-action="Create">Create New Ticket</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Free carry-on bag #</th>
            <th>Checked-in bag #</th>
            <th>Trolley Bag#</th>
            <th>Destination</th>
            <th>Profile Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FreeCarry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckedIn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrolleyBag)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Flight.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Passenger.FirstName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<div class="form-group">
    <input type="button" value="List of Passengers" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "PassengerInfoes")'" />
    <input type="button" value="List of Flights" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "FlightInfoes")'" />
</div>