Nebb.WebApi/Controllers/FlightInfoesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nebb.Data.Models;

namespace Nebb.WebApi.Controllers
{
    public class FlightInfoesController : Controller
    {
        private readonly NebbContext _context;

        public FlightInfoesController(NebbContext context)
        {
            _context = context;
        }

        // GET: FlightInfoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.FlightInfo.ToListAsync());
        }

        // GET: FlightInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightInfo = await _context.FlightInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flightInfo == null)
            {
                return NotFound();
            }

            return View(flightInfo);
        }

        // GET: FlightInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FlightInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Origin,Destination,Departure,ReturnDay")] FlightInfo flightInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flightInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flightInfo);
        }

        // GET: FlightInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightInfo = await _context.FlightInfo.FindAsync(id);
            if (flightInfo == null)
            {
                return NotFound();
            }
            return View(flightInfo);
        }

        // POST: FlightInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Origin,Destination,Departure,ReturnDay")] FlightInfo flightInfo)
        {
            if (id != flightInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flightInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightInfoExists(flightInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flightInfo);
        }

        // GET: FlightInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightInfo = await _context.FlightInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flightInfo == null)
            {
                return NotFound();
            }

            return View(flightInfo);
        }

        // POST: FlightInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flightInfo = await _context.FlightInfo.FindAsync(id);
            _context.FlightInfo.Remove(flightInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightInfoExists(int id)
        {
            return _context.FlightInfo.Any(e => e.Id == id);
        }
    }
}

Nebb.WebApi/Controllers/PassengerInfoesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nebb.Data.Models;

namespace Nebb.WebApi.Controllers
{
    public class PassengerInfoesController : Controller
    {
        private readonly NebbContext _context;

        public PassengerInfoesController(NebbContext context)
        {
            _context = context;
        }

        // GET: PassengerInfoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.PassengerInfo.ToListAsync());
        }

        // GET: PassengerInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengerInfo = await _context.PassengerInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (passengerInfo == null)
            {
                return NotFound();
            }

            return View(passengerInfo);
        }

        // GET: PassengerInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PassengerInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,DateOfBirth,Passport,LoyalMemberId,UseLoyalMember")] PassengerInfo passengerInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(passengerInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(passengerInfo);
        }

        // GET: PassengerInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengerInfo = await _context.PassengerInfo.FindAsync(id);
            if (passengerInfo == null)
            {
                return NotFound();
            }
            return View(passengerInfo);
        }

        // POST: PassengerInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,DateOfBirth,Passport,LoyalMemberId,UseLoyalMember")] PassengerInfo passengerInfo)
        {
            if (id != passengerInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(passengerInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PassengerInfoExists(passengerInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(passengerInfo);
        }

        // GET: PassengerInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengerInfo = await _context.PassengerInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (passengerInfo == null)
            {
                return NotFound();
            }

            return View(passengerInfo);
        }

        // POST: PassengerInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var passengerInfo = await _context.PassengerInfo.FindAsync(id);
            _context.PassengerInfo.Remove(passengerInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PassengerInfoExists(int id)
        {
            return _context.PassengerInfo.Any(e => e.Id == id);
        }
    }
}

Nebb.WebApi/Controllers/TicketsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nebb.Data.Models;

namespace Nebb.WebApi.Controllers
{
    public class TicketsController : Controller
    {
        private readonly NebbContext _context;

        public TicketsController(NebbContext context)
        {
            _context = context;
        }

      //  GET: Tickets
        public async Task<IActionResult> Index()
        {
            var nebbContext = _context.Ticket.Include(t => t.Flight).Include(t => t.Passenger);
            return View(await nebbContext.ToListAsync());
        }

       // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Flight)
                .Include(t => t.Passenger)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

       // GET: Tickets/Create
        public IActionResult Create()
        {
            ViewData["FlightId"] = new SelectList(_context.FlightInfo, "Id", "Destination");
            ViewData["PassengerId"] = new SelectList(_context.PassengerInfo, "Id", "FirstName");
            return View();
        }

        // POST: Tickets/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FreeCarry,CheckedIn,TrolleyBag,PassengerId,FlightId")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlightId"] = new SelectList(_context.FlightInfo, "Id", "Destination", ticket.FlightId);
            ViewData["PassengerId"] = new SelectList(_context.PassengerInfo, "Id", "FirstName", ticket.PassengerId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["FlightId"] = new SelectList(_context.FlightInfo, "Id", "Destination", ticket.FlightId);
            ViewData["PassengerId"] = new SelectList(_context.PassengerInfo, "Id", "FirstName", ticket.PassengerId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FreeCarry,CheckedIn,TrolleyBag,PassengerId,FlightId")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlightId"] = new SelectList(_context.FlightInfo, "Id", "Destination", ticket.FlightId);
            ViewData["PassengerId"] = new SelectList(_context.PassengerInfo, "Id", "FirstName", ticket.PassengerId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Flight)
                .Include(t => t.Passenger)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Ticket.FindAsync(id);
            _context.Ticket.Remove(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Ticket.Any(e => e.Id == id);
        }
    }
}

Nebb.WebApi/Views/PassengerInfoes/Create.cshtml
@model Nebb.Data.Models.PassengerInfo

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create your profile</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Date of Birth</label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Passport" class="control-label">Passport Number</label>
                <input asp-for="Passport" class="form-control" />
                <span asp-validation-for="Passport" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoyalMemberId" class="control-label">Loyal Member ID:</label>
                <input asp-for="LoyalMemberId" class="form-control" />
                <span asp-validation-for="LoyalMemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UseLoyalMember" class="control-label">Do you want to use your loyal member credits?</label>
                <input asp-for="UseLoyalMember" class="form-control" />
                <span asp-validation-for="UseLoyalMember" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Nebb.WebApi/Views/PassengerInfoes/Delete.cshtml
@model Nebb.Data.Models.PassengerInfo

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete profile</h1>

<h3>Are you sure you want to delete this profile?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">First Name</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">Last Name</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">Date of Birth</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">Passport Number</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Passport)
        </dd>
        <dt class = "col-sm-2">Loyal Member ID:</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoyalMemberId)
        </dd>
        <dt class = "col-sm-2">Using loyal member?</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UseLoyalMember)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Nebb.WebApi/Views/PassengerInfoes/Details.cshtml
@model Nebb.Data.Models.PassengerInfo

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Passenger Informations</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">First Name</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">Last Name</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">Date of Birth</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">Passport Number</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Passport)
        </dd>
        <dt class = "col-sm-2">Loyal Member ID:</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoyalMemberId)
        </dd>
        <dt class = "col-sm-2">Using loyal member credits?</dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UseLoyalMember)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Nebb.WebApi/Views/PassengerInfoes/Edit.cshtml
@model Nebb.Data.Models.PassengerInfo

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit profile</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Date of Birth</label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Passport" class="control-label">Passport Number</label>
                <input asp-for="Passport" class="form-control" />
                <span asp-validation-for="Passport" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoyalMemberId" class="control-label">Loyal Member ID:</label>
                <input asp-for="LoyalMemberId" class="form-control" />
                <span asp-validation-for="LoyalMemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UseLoyalMember" class="control-label">Do you want to use your loyal member credits?</label>
                <input asp-for="UseLoyalMember" class="form-control" />
                <span asp-validation-for="UseLoyalMember" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Nebb.WebApi/Views/PassengerInfoes/Index.cshtml
@model IEnumerable<Nebb.Data.Models.PassengerInfo>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List of passengers</h1>
<p>
    <a asp-action="Create">Create New profile</a>
</p>
<div class="form-group">
    <input type="button" value="Reserver Flight" class="btn btn-primary" onclick="window.location='@Url.Action("Create", "FlightInfoes")'" />
    <input type="button" value="List of Flights" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "FlightInfoes")'" />
</div>
<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Date of Birth</th>
            <th>Passport Number</th>
            <th>Loyal Member ID:</th>
            <th>Using loyal member credits?</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Passport)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoyalMemberId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UseLoyalMember)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<div class="form-group">
    <input type="button" value="List of Tickets" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "Tickets")'" />
    <input type="button" value="List of Flights" class="btn btn-primary" onclick="window.location='@Url.Action("Index", "FlightInfoes")'" />
</div>